version: '3'

services:

  hello_world_42go:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: unless-stopped
    # volumes:
    #   - ./:/app
    entrypoint:
    - bash
    - -c
    - ./main